### ISSUE TITLE
Recuperar Senha

### ISSUE THREAD

**Issue by alanvillela** [DevPetaSoft/CamaraAlertaAndroid#14]
Implementar funcionalidade para Recuperar Senha (esqueci minha senha), na qual envia uma nova senha para o e-mail do usuário cadastrado. 

Para recuperar a senha, utilizar o CPF como campo obrigatório.

**Comment by gudominguete** [comment]
CPF nao pode ser campo obrigatório pois ele é facultativo em todo o sistema
