### ISSUE TITLE
Usuario não encontrado - Recuperar senha

### ISSUE THREAD

**Issue by alanvillela** [DevPetaSoft/CamaraAlertaAndroid#30]
Após recuperar a senha e tentar realizar o login, uma mensagem de que o usuario não foi encontrado é exibida.
Ao tentar cadastrar com o mesmo email, informa que o email já foi cadastrado.

![whatsapp image 2017-02-14 at 18 43 41](https://cloud.githubusercontent.com/assets/11199593/22948426/a5d6ab8a-f2e5-11e6-8395-2360563f3757.jpeg)

**Comment by gudominguete** [comment]
Esse problema acontece pq a recuperação de senha já está vindo com a hash, e o app está enviando a senha pura, acredito que quando for arrumar essa parte de criptografia, essa issue será resolvida junta.
