### ISSUE TITLE
Confirmação - Recuperar Senha

### ISSUE THREAD

**Issue by alanvillela** [DevPetaSoft/CamaraAlertaAndroid#31]
Ao inserir o email e clicar em recuperar senha, o app volta pra tela inicial mas não exibe mais a mensagem que o email de recuperação foi enviado.

É necessario que volte pra tela inicial e exiba um feedback confirmando que a solicitacao de recuperar senha foi aceita.

**Comment by lucaslemosb** [comment]
Após alguns testes no app todos me deram a mensagem na parte inferior da tela pedindo para checar o email. Você ainda consegue replicar esse problema?

**Comment by alanvillela** [comment]
Deu certo
